### ISSUE TITLE
Armour staying on when you don't get kicked

### ISSUE THREAD

**Issue by MrNoisyKidd** [MCGamerNetwork/Issues#662] opened 2015-06-14 09:46 UTC
I won a game previously and it didn't kick me; breeze island started and it deleted all stuff apart from my armour.

![](http://i.imgur.com/6WB5Wuu.png)

**Comment by WildcatGecko** [comment] 2015-06-15 14:04
This is also a problem in SGClassic.

**Comment by forairan** [comment] 2015-07-21 01:21
Duplicate of #641.

**Closed by forairan** 2015-07-21 01:21 UTC
