### ISSUE TITLE
Battlegrounds fight in Warp Room

### ISSUE THREAD

**Issue by GeckoG** [MCGamerNetwork/Issues#836] opened 2015-11-13 02:00 UTC
Environment
I've noticed this on all US Battlegrounds servers, and it is possible it is on other regions as well. It is on the ice map, and happens every time the map rolls around.

    The issue
You are able to damage and kill other players in the warp/starting room in the ice map of battlegrounds. It will award you golden apples and points as well. If you stand on blocks that are higher than the floor, you are immune, and the same goes for when you jump, so the pvp zone must be 1 block too high.

    Steps to reproduce
Find a Battlegrounds server running the ice map and try punching another player.

    Miscellaneous information
N/A

**Comment by forairan** [comment] 2015-11-29 09:36
Duplicate of #826.

**Closed by forairan** 2015-11-29 09:36 UTC
