### ISSUE TITLE
Invisible People/ No teer two Chests

### ISSUE THREAD

**Issue by TacoKittyFTW** [MCGamerNetwork/Issues#547] opened 2015-02-03 15:17 UTC
Environment: US Servers

Issue: While In a game two out of the four games of survival games I played, there were no teer two chests. Also In these games but not in others there were occasionally invisible people. They could see me but I couldn't see them, I don't think this was intentional but it poses an unfair advantage.

I have no ways of reproducing this bug, it simply happened randomly and I have no way of finding a game like those two unless I join multiple games and look for these bugs myself.

**Comment by forairan** [comment] 2015-02-03 15:20
One issue per report, please. Also, duplicate of #541 and #542.

**Closed by forairan** 2015-02-03 15:20 UTC
