### ISSUE TITLE
Keeping Armor From Previous Game Bug

### ISSUE THREAD

**Issue by josh155** [MCGamerNetwork/Issues#670] opened 2015-06-21 14:24 UTC
Hello, I noticed another bug. Basically if you win a game and it puts you to the lobby but doesn't kick you then you keep your armor you had from the previous game. Screenshot proof. https://gyazo.com/2ad2311c105fa0b072aeea7e83b12543

**Comment by forairan** [comment] 2015-07-21 01:21
Duplicate of #641.

**Closed by forairan** 2015-07-21 01:21 UTC
