### ISSUE TITLE
Platinums Cannot Kick Certain Users

### ISSUE THREAD

**Issue by ButterScottch** [MCGamerNetwork/Issues#521] opened 2015-01-10 23:10 UTC
*Environment* 
All regions, all servers.

*The Issue*
Platinums cannot kick gold or iron donors.

*Steps to Reproduce*
1) Get a platinum alt in-game.
2) Try to join a game filled with no normal members, and at least 1 iron/gold donors.

*Miscellaneous Information*
N/A

**Comment by subv3rsion** [comment] 2015-01-25 04:30
Duplicate of #507

**Closed by subv3rsion** 2015-01-25 04:30 UTC
