### ISSUE TITLE
Last to join; better hits.

### ISSUE THREAD

**Issue by 4Devianz** [MCGamerNetwork/Issues#721] opened 2015-07-25 18:36 UTC
1: This issue is universal on MCGamer. It works on all of the hosts. Most common on Survival Games.
2: There are other servers with this problem, the "relog glitch." How it works is, supposedly the last person to join a game will have better hits than the first. 
3: How this can be reproduced is by being the last one to join the game. Now provide the scenario where two players fight. Player A was the first to join. However Player B was the last. They have even gear, however nine times out of ten, Player B will have better hits.

**Comment by forairan** [comment] 2015-07-25 23:37
Duplicate of #710.

**Closed by forairan** 2015-07-25 23:37 UTC
