### ISSUE TITLE
Bounty Glitch

### ISSUE THREAD

**Issue by Tawklo** [MCGamerNetwork/Issues#509] opened 2015-01-01 01:19 UTC
On any Survival Games server

/bounty player POINTS does not work properly

Do /bounty player POINTS then /confirmbounty and you cannot place a bounty; however, sponsoring works.

**Comment by KitMencha** [comment] 2015-01-01 04:43
Duplicate of #491 and #478

**Closed by KitMencha** 2015-01-01 04:43 UTC
