### ISSUE TITLE
Flying in Deadly Descent

### ISSUE THREAD

**Issue by vanicle** [MCGamerNetwork/Issues#708] opened 2015-07-17 19:40 UTC
Gametype: Deadly Descent:

Issue: donors and moderators can fly in Deadly Descent, after typing /fly to go out of that mode, they receive the following error message: http://prntscr.com/7tvujm

When participants are flying, they take no damage and can race to the bottom.

Steps to replicate: fly in Deadly Descent

Misc: none

**Comment by forairan** [comment] 2015-08-06 02:43
I'm unable to reproduce this issue as a platinum. Is this still an issue?

**Comment by YourAverageTiger** [comment] 2015-08-06 22:10
I managed to get a recording of myself reproducing the issue. Prior to doing do I did recieve Administration permission.
https://youtu.be/mJVKFya2GHE
@forairan

**Comment by YourAverageTiger** [comment] 2015-08-06 22:13
I went in Gamemaster. If you do not want to watch the full video you can skip to 1 minute 20 seconds and start from there.

**Comment by forairan** [comment] 2015-08-20 04:21
Thanks - the video was very helpful in resolving the issue.
The issue will be resolved as of the next deployment cycle.

**Closed** 2015-08-20 04:20 UTC
