### ISSUE TITLE
Flint and Steel Glitch

### ISSUE THREAD

**Issue by iRocki** [MCGamerNetwork/Issues#898] opened 2016-01-30 03:28 UTC
I know this issue has been brought up multiple times and I know it is used to prevent macro users but whenever I use the flint and steel very fast then it places for one second and disappears.

**Comment by Envici** [comment] 2016-01-30 04:55
Duplicate of #891 and has already been fixed. As CAm stated, it will be resolved in the next update.

**Comment by arsenalfcgunners** [comment] 2016-02-06 02:10
Even with the last update the glitch is still occurring.  https://youtu.be/PVoxQr1_pok

**Closed** 2016-02-07 18:28 UTC
