### ISSUE TITLE
/join sg sends members to the hub 90% of the time

### ISSUE THREAD

**Issue by sontate72** [MCGamerNetwork/Issues#664] opened 2015-06-16 13:49 UTC
Environment
US Survival Games. ID #7405

The issue
It appears the glitch has came back: when a member does "/join sg" or "/watch sg", it will often send them back to the hub. The error normally states that the game is full. Sometimes the command will work, but there's a very high chance you'll join a 23-man game, and then just be kicked again.

For /watch, the game will sometimes state "You cannot join during PreGame." if it doesn't connect you.

Steps to reproduce
1.Type /join sg and/or /watch sg as a member.
2. Repeat. Soon enough, you will see the issue.

**Comment by JLioner** [comment] 2015-07-03 16:43
^^^^^^^^
The issue is, that /join or /watch sg tries to enter a full lobby/game. That is great if you are a donor, but if you are a regular player, you cannot use that command at all.
What makes it even worse, is, that /join sg always tries to join the same lobby until this one ended (see video). 
Video: https://www.youtube.com/watch?v=t21NSRIAfVI

**Comment by forairan** [comment] 2015-08-20 01:05
See #602 - effectively fixed as of the next deployment cycle.

**Closed by forairan** 2015-08-20 01:05 UTC
