### ISSUE TITLE
Incorrect Block in Hub

### ISSUE THREAD

**Issue by Azuraii** [MCGamerNetwork/Issues#530] opened 2015-01-18 02:59 UTC
Environment: Hub
The issue: There should be a leaf here: http://imgur.com/quPKoZQ
Steps to reproduce: 
Step 1: TP to x:221, y:17, z:346
Step 2: Put a leaf there.

**Comment by Muix** [comment] 2015-01-18 07:06
Leaf xD

**Comment by KitMencha** [comment] 2015-01-19 03:10
Duplicate of #503

**Closed by KitMencha** 2015-01-19 03:10 UTC
Labels: duplicate
