### ISSUE TITLE
Lobby PVP on BattleGrounds.[High Priority]

### ISSUE THREAD

**Issue by CloneMCG** [MCGamerNetwork/Issues#568] opened 2015-02-15 13:52 UTC
I was playing on the US.MCGamer.net IP and went on a few gamemodes to make sure things were going well, I came across a bug when I joined a BG game, I was taking damage in the pre-game center(Not the BG hub, all of the game lobbies) 

This issue is very simple to duplicate, all players are affected by this and it needs to get fixed quickly, many hackers have just been coming through the lobbies and camping by spawn there, it's nearly impossible to record as you take too much damage and it's too crowded with players.

Hope it gets fixed soon.

**Comment by subv3rsion** [comment] 2015-04-07 06:51
Duplicate of #308.

**Closed by subv3rsion** 2015-04-07 06:51 UTC
