### ISSUE TITLE
Unable to leave parties

### ISSUE THREAD

**Issue by JLioner** [MCGamerNetwork/Issues#620] opened 2015-04-19 18:38 UTC
==== Environment ====

Only tested on EU, probably all locations

==== The issue ====

If you are in a party and do /party leave you do not actually leave the party. However if you do /party leave or /party list after that, then it sais "You must be in a party for that", but you will still get teleported in another lobby if the leader does /party warp.
Not even disconnecting helps here, you will still get warped in. (Also while being in Gamemaster)

==== Steps to reproduce ====

^^^^^^

==== Miscellaneous information ====

---

**Comment by subv3rsion** [comment] 2015-04-19 23:36
Duplicate of #513

**Closed by subv3rsion** 2015-04-19 23:36 UTC
