### ISSUE TITLE
lot of bugs

### ISSUE THREAD

**Issue by xArticHD** [MCGamerNetwork/Issues#540] opened 2015-02-03 09:11 UTC
There are invisble players and all tier 2's are empty

**Comment by ButterScottch** [comment] 2015-02-03 14:05
That provides little information. Make sure to follow the template at the bottom of this page: https://github.com/MCGamerNetwork/Issues

**Comment by forairan** [comment] 2015-02-03 14:56
Not enough information. Closed as a duplicate of #541 and #542, which have more information.

**Closed by forairan** 2015-02-03 14:56 UTC
