### ISSUE TITLE
Battle Grounds - Grace & Warp

### ISSUE THREAD

**Issue by ApexMC** [MCGamerNetwork/Issues#927] opened 2016-02-29 23:37 UTC
With the new battlegrounds features, there are a few bugs to come with it. For starters there is a small "grace period" in battlegrounds where nobody can hit you for about 10 seconds or until you hit another player. This does not apply to fire so someone can place fire on the spawn point and people will start being hurt by fire.

Next the warp within the compass in battlegrounds come up with an invalid warp when they are clicked. There is an attached video to display both of these.

Video:
https://www.youtube.com/watch?v=juQDpJYX9XM&feature=youtu.be

**Comment by arsenalfcgunners** [comment] 2016-03-01 05:15
The FNS is a duplicate of #929. As for the warp issue that is a bug for sure!

**Comment by arsenalfcgunners** [comment] 2016-03-01 05:16
And you did report it first so yeah my fault. I will close mine. xD I didn't see this.

**Comment by CAmadeusA** [comment] 2016-03-02 07:34
Hey! This will be resolved in the next update. Thank you for reporting. Have a great day!

**Closed by CAmadeusA** 2016-03-02 07:34 UTC
