### ISSUE TITLE
BattleGrounds Bug Report

### ISSUE THREAD

**Issue by KorayHalacoglu** [MCGamerNetwork/Issues#713] opened 2015-07-20 07:12 UTC
BattleGrounds Bug report https://www.youtube.com/watch?v=ETsyp3Ul078

apply http://www.mcgamer.net/threads/korayhalacoglu-moderator-application.204098/

Please Mcgamer Credits..

**Comment by forairan** [comment] 2015-07-21 00:53
Duplicate of #716.

**Closed by forairan** 2015-07-21 00:53 UTC
