### ISSUE TITLE
/server sg

### ISSUE THREAD

**Issue by adwianwodwiguez** [MCGamerNetwork/Issues#582] opened 2015-03-01 06:10 UTC
I have had a reoccuring problem since the 1.8 update in which 99.9% of the time I type /server sg it connects me back to the hub either saying it's full or in PreGame. Excuses would sound to me like "Well, duh if the games full it won't direct you", BUT I am saying that I am a donor and when I type /server sg I want to get into a game full or not! Also the pregame thing is just stupid - The server is basically at war with itself right now. Sorry.

**Comment by subv3rsion** [comment] 2015-04-18 07:43
Duplicate of #602

**Closed by subv3rsion** 2015-04-18 07:43 UTC
