### ISSUE TITLE
/scramble & /bounty system not working 

### ISSUE THREAD

**Issue by scott46743** [MCGamerNetwork/Issues#516] opened 2015-01-08 00:23 UTC
*Environment* 
All regions, servers.

*The Issue* 
/bounty is not working for all users.
/scramble & /unscramble are not working for all users, even though it is for platinums+ (as reported in #349 )

*Steps to Reproduce*
1) Go into an SG game as a platinum.
2) Try to /bounty someone and /scramble.

*Miscellaneous Information*
Was reported multiple times, as well as tested by Neph.

**Comment by xXCarterHDXx** [comment] 2015-01-08 01:49
Thanks for answering my thread. (RebornUS) :+1:

**Comment by KitMencha** [comment] 2015-01-08 01:51
This will be fixed in the next plugin push. Thanks for the report!
Duplicate of #478

**Closed by KitMencha** 2015-01-08 01:51 UTC
Labels: duplicate
