### ISSUE TITLE
Battlegrounds "Gamemaster" Visibility Glitch

### ISSUE THREAD

**Issue by ApexMC** [MCGamerNetwork/Issues#899] opened 2016-01-30 19:08 UTC
So while in battlegrounds I have noticed that people can easily see my floating head while they are in the game. Here is a clip as an example when I was in battlegrounds spectating a hacker. 

https://www.youtube.com/watch?v=J_OKTE-WhxI&feature=youtu.be

**Comment by arsenalfcgunners** [comment] 2016-02-03 05:14
Duplicate of #763 :P

**Closed** 2016-06-09 21:24 UTC
