### ISSUE TITLE
Book in Hubs

### ISSUE THREAD

**Issue by ButterScottch** [MCGamerNetwork/Issues#524] opened 2015-01-11 05:02 UTC
*Environment*
Hubs, all regions.

*The Issue*
The book that is supposed to contain front page news only contains an error message. "* Invalid Book Tag *"

*Steps to Reproduce* 
N/A

*Miscellaneous Information*
http://i.imgur.com/72du9Iw.jpg

**Comment by subv3rsion** [comment] 2015-01-25 04:20
I've mentioned the cause of this to the devs, but to confirm, I've made some adjustments where the US and AU networks should be able to see the books. This may take a restart of our servers to take effect.

If this fixes the problem, we will apply the fix to all locations.

**Comment by arsenalfcgunners** [comment] 2015-01-26 07:45
I can confirm this is still an issue even after last nights update.

**Comment by subv3rsion** [comment] 2015-04-18 10:09
This appears to no longer be an issue. As this is resolved, I will go ahead and close this issue. Thanks for the report!

**Closed by subv3rsion** 2015-04-18 10:09 UTC
