### ISSUE TITLE
FNS, Bow and Food Glitches

### ISSUE THREAD

**Issue by ModLuflexed** [MCGamerNetwork/Issues#946] opened 2016-03-15 01:51 UTC
I have seen several reports of the FNS glitch still relevant.

Also I have seen new reports of people not being able to shoot a bow sometimes or eat food.

**Comment by arsenalfcgunners** [comment] 2016-03-17 02:40
#945 #846 #944

**Comment by forairan** [comment] 2016-03-27 01:55
Duplicate of the above listed issues.

**Closed by forairan** 2016-03-27 01:55 UTC
