### ISSUE TITLE
Battlegrounds Hearts and LeaderBoards Error

### ISSUE THREAD

**Issue by FlopperDoesGames** [MCGamerNetwork/Issues#618] opened 2015-04-08 22:03 UTC
In this game mode , sometimes the leaderboards are not seen in the game, not the hearts up player
I happen to me in every game . My friends also will occur this
Proof : http://imgur.com/RpXK05r

**Comment by subv3rsion** [comment] 2015-04-17 18:29
Can you elaborate on what you're experiencing with the player hearts? Are you referring to the indicator showing how much health a player has left over?

This sounds to be a duplicate of #604, but just need confirmation regarding the second half.

**Comment by subv3rsion** [comment] 2015-04-20 22:35
Assuming this is a duplicate of #604.

**Closed by subv3rsion** 2015-04-20 22:35 UTC
