### ISSUE TITLE
Internal Exception when joining a hub sometimes.

### ISSUE THREAD

**Issue by FusionDeck** [MCGamerNetwork/Issues#707] opened 2015-07-17 02:25 UTC
Location: US (May occur on other locations too, not sure)

Issue: Sometimes when switching to a hub (via the hub selector in the lobby) or via /hub, the player gets kicked with an internal exception. (Kick message: http://gyazo.com/6e3c0266091697365d1f882f3d101a5e)

To reproduce: Use /hub or select a hub on the hub selector GUI (only occurs on occasions).

**Comment by AGFire2013** [comment] 2015-07-17 16:59
^Happening for a lot of players

**Comment by Alkan1** [comment] 2015-07-19 11:03
When I joined to US it happened to me too, but not happening in EU

**Comment by forairan** [comment] 2015-07-21 01:24
Should be fixed now, please do open a new issue if the issue is still occurring.

**Closed by forairan** 2015-07-21 01:24 UTC
