### ISSUE TITLE
Spectator/GameMaster Glitch [Dump ID #317]

### ISSUE THREAD

**Issue by Ceroria** [MCGamerNetwork/Issues#636] opened 2015-05-02 15:26 UTC
Happens often in Survival Games matches.  I could go into almost any Survival Games match and participants can see spectators as if they were players.  This glitch occurred at the beginning of the release of MCGamer V2 as well.  

For the gamemaster glitch, I joined another game to spectate a hacker (Dump ID #323, also occured in another server, got Dump ID #325) and was visible to every player and spectator, just like as in the previously mentioned spectator glitch.

Still getting the hang of GitHub, hopefully that was the right way to implement the Dump IDs ;-;

**Comment by subv3rsion** [comment] 2015-05-03 01:08
Duplicate of #634, but thank for the additional information! I will make note of this in the other issue.

**Closed by subv3rsion** 2015-05-03 01:08 UTC
