### ISSUE TITLE
All the bugs within the server right now!

### ISSUE THREAD

**Issue by nikolafeelzzhd** [MCGamerNetwork/Issues#841] opened 2015-11-21 15:04 UTC
Note to developers; I will report this on hubgub issue (whatsoever), but I decided to post it on this thread as well just because I want to know if I missed some bugs:

In-game:

- Eating bug: Self-explanatory. Sometimes it won't eat food for some odd reason.

- Bow bug: When I try to shoot with the bow, sometimes it won't actually release the arrow.

- Eating things twice in a row: Now this is really a game-changing bug just because you can eat something while running. For an example, if you have 2 golden apples and you ate one but you still kept the other one in your hand, you can basically run while eating the second one. This can be confusing because mods could potentially ban you for no slowdown.

- FnS bug: I'm pretty sure this is somewhat familiar to you guys.

- Armour bug: Well, sometimes when I try to put my armour it would actually show that I have it on but from other players perspectives it wouldn't. After 20-30 seconds instead of me wearing it, it would show up in one of my inventory slots.

**Comment by forairan** [comment] 2015-11-28 04:36
I've split out two of the issues reported here into separate issues. However, in the future, please submit separate issue reports for each issue, as it's easier for us to keep track of that way (and saves us time from having to manually split the issues).

Eating (both issues): potential duplicate of #817.
Flint and steel: duplicate of issue #821.
Bow: split to issue #846.
Armor: split to issue #847.

**Closed by forairan** 2015-11-28 04:36 UTC
