### ISSUE TITLE
Breaking ladders

### ISSUE THREAD

**Issue by ServerOfTheAltar** [MCGamerNetwork/Issues#605] opened 2015-04-02 02:25 UTC
When the back of a bottom ladder is set on fire in SG, the whole ladder breaks.

**Comment by subv3rsion** [comment] 2015-04-20 22:44
@forairan and I agree that this is unintentional, but hilarious. If you light a ladder on fire, you're likely not going to get up it anyway.
Marking as (unintentionally) working as intended.

Thanks for the report!

**Closed by subv3rsion** 2015-04-20 22:44 UTC
