### ISSUE TITLE
Login glitch not patched

### ISSUE THREAD

**Issue by fukwitme** [MCGamerNetwork/Issues#809] opened 2015-10-06 12:46 UTC
*pasting Ceroria's bug report which referenced my thread/video*

"This issue occurs on all of our networks, and effects the entire server, however it is only a problem in the gamemodes that require PvP, such as Deadly Descent, Battlegrounds, and Survival Games. This issue occurs in every match of these gamemodes played.

This issue is not specific to MCGamer, however there is a way to patch it. What the issue is, is the order in which a player logs into a server affects the amount of knockback they take, which is a major game-changing factor in the Survival Games. Say Player A joins the server (1/24) and Player B joins the server (2/24). Player A will take twice the knockback Player B will take (Player B takes 1 block, Player A takes 2 blocks) therefore any player who logs into the server AFTER another player will have a DISTINCT advantage over the other in a match of Survival Games/Battlegrounds/Deadly Descent. For further explanation of this glitch, a video has been made by RasclartsReloaded which can be found here https://youtu.be/MesZOuwcuvo, and a thread made on it on the MCGamer Forums can be found here http://www.mcgamer.net/threads/relog-glitch.204172/#post-2075821

This issue can be experienced by simply joining, for example, any Survival Games match.

This glitch is patchable, and has been patched by most potion PvP servers such as ParaPvP, Kohi, Badlion, etc."

I've noticed that the issue hasn't been fixed yet. It really needs to be a top priority as currently sword fighting is just a pointless exercise. Here are two existing, publicly available fixes:
https://www.spigotmc.org/resources/knockbackfixer.6388/
https://github.com/OvercastNetwork/SportBukkit/commit/0a6819e11487d6fef0b5bdc4fbd635ef8a512101

I understand that it's MCGamer's policy to have its own custom plugins, so could something be coded similarly to one of those plugins without plagiarising?

**Comment by forairan** [comment] 2015-10-07 18:51
Duplicate of #710 - please see that issue for updates. Intentionally creating duplicate issues doesn't speed up the process of fixing things, but rather slows it down, as we have to deal with information in multiple places.

**Closed by forairan** 2015-10-07 18:51 UTC
