### ISSUE TITLE
Friend Issue 

### ISSUE THREAD

**Issue by Jurud** [MCGamerNetwork/Issues#652] opened 2015-05-18 01:52 UTC
Environment: US Region, 5/17/2015/Hub-All Gametypes

The issue: It seems whenever I do the commands "/friends", "/friend list", and "/friend add" nothing seems to happen, it seems to be an issue on all of the servers for me. 

Steps to reproduce:
Just type: /friends, /friends list, and /friend add 

Miscellaneous information: "Evidence" wise, I can't really give anything to support my case. 
(BTW: I am a moderator, if it is a ranking issue or whatnot) 

State Dump ID #2686

**Comment by arsenalfcgunners** [comment] 2015-05-18 05:47
Not working for me either.  I tried /friend list 1 also instead of just /friend list.  None of them worked, even /friends.

**Comment by forairan** [comment] 2015-05-30 22:49
I can't reproduce this issue; are you still having an issue with it?

**Comment by arsenalfcgunners** [comment] 2015-05-31 05:33
Devin did each players friends reset with the update?  I believe what is happening is that when you do /friends and you have 0 friends it just prints nothing.  Maybe make it so it says "You don't haven't added any friends yet."  or something like that.

**Comment by subv3rsion** [comment] 2015-05-31 23:40
This has been resolved, and will be live with the latest plugin push. 
There may still be some unfriendly prompts by the friend system, which we should be resolving either tonight or with the next plugin push.

@arsenalfcgunners Friends have not been reset, but this error may have come up from what had been broken.

Thanks for the report!

**Closed by subv3rsion** 2015-05-31 23:40 UTC
Labels: cannot-reproduce
