### ISSUE TITLE
Seen In Gamemaster

### ISSUE THREAD

**Issue by WildcatGecko** [MCGamerNetwork/Issues#745] opened 2015-08-13 16:49 UTC
1. Environment)This can be done in-game of SG or SGSolo, on any server in any region. It can be reproduced at any time.
2. The Issue) All in-game players can see your whole body.
3. Reproduction) Steps to reproduce:
i) Start on 1.7
ii) Join a SG or SGSolo lobby, not in gamemaster
iii) Switch to gamemaster
iv) wait for game to start
4. Misc Info) This is done on 1.7 and I have not tried it on 1.8 yet. It is possible that it can be done on both versions.

**Comment by arsenalfcgunners** [comment] 2015-08-14 04:59
Seems to only happen occasionally. Not sure what causes it to happen.

**Comment by YourAverageTiger** [comment] 2015-08-16 15:28
Shows your head and raw nametag on 1.8 spectating/gamemaster.

**Comment by forairan** [comment] 2015-08-16 23:41
Duplicate of #668.

**Closed by forairan** 2015-08-16 23:41 UTC
