### ISSUE TITLE
Right Click Fire

### ISSUE THREAD

**Issue by HomeGoods** [MCGamerNetwork/Issues#941] opened 2016-03-05 10:48 UTC
Environment

This section should provide all information regarding the environment where the issue occured, location (US/EU/CA/AU), server ID, gametype, time of when the issue happened, etc.

The issue

When you right click wood on EU it will turn into fire (1.7.10)

Steps to reproduce

Go on EU (1672 is where this happened) and right click wood and it will turn into fire.

Miscellaneous information

https://www.youtube.com/watch?v=Fxm-ZnDrkfE

**Comment by Envici** [comment] 2016-03-06 06:27
Duplicate of #934 which was already fixed/closed.

**Comment by VigiloMCGamer** [comment] 2016-03-09 16:17
This is still going on. It recently happened to me: https://www.youtube.com/watch?v=TCY2pgHkNsg&feature=youtu.be

**Comment by CAmadeusA** [comment] 2016-03-09 17:03
It _is_ resolved on the beta servers, or at least it should be. Could you tell me if its happening on a beta server?

**Comment by arsenalfcgunners** [comment] 2016-03-11 23:00
@CAmadeusA maybe where it says the server number in the sidebar it should say "(Beta)" after that. That way it is easy to tell if the glitch that was reported was on a beta or a stable server.

**Comment by forairan** [comment] 2016-03-12 02:31
@arsenalfcgunners Not enough room for that due to Minecraft limitations.

**Comment by arsenalfcgunners** [comment] 2016-03-12 02:49
@forairan I know that it is limited to 16 characters, but is there a reason why you cannot do the team work around where you create a team, and then use the prefix and suffix to gain extra characters? You could also maybe just do "(b)" to make it shorter.

**Comment by CAmadeusA** [comment] 2016-04-08 19:28
This issue has been resolved. Thank you for reporting, have a great day.

**Closed by CAmadeusA** 2016-04-08 19:28 UTC
