### ISSUE TITLE
Blockhitting issue

### ISSUE THREAD

**Issue by 3point14** [MCGamerNetwork/Issues#702] opened 2015-07-13 00:40 UTC
US MCSG Servers
Blockhitting makes it so none of your remaining hits register.
Blockhit and it'l happen.
https://www.youtube.com/watch?v=4ACgJve3C48

**Comment by forairan** [comment] 2015-07-25 23:53
Duplicate of #683.

**Closed by forairan** 2015-07-25 23:53 UTC
