### ISSUE TITLE
Party feature

### ISSUE THREAD

**Issue by jeffreychan1999** [MCGamerNetwork/Issues#596] opened 2015-03-18 14:57 UTC
My in game name is SixPacks, and today on the U.S. servers playing MCSG, I accepted a party request from a random person. I wanted to leave the party but it says I'm not in the party. However the party leader can teleport and summon me, which interrupted many of my games which I was close to winning. The party leader claimed that he kicked me from the party but he still keeps summoning me and his party mates to his server which is really annoying. I hope you fix this, thank you.

**Comment by subv3rsion** [comment] 2015-04-20 22:08
Duplicate of #513

**Closed by subv3rsion** 2015-04-20 22:08 UTC
