### ISSUE TITLE
Pets In Game

### ISSUE THREAD

**Issue by ButterScottch** [MCGamerNetwork/Issues#519] opened 2015-01-09 18:29 UTC
*Environment*
SG Games, All Regions

*The Issue*
Pets, specifically spiders, have been found as a spectator in SG Games.

*Steps to Reproduce* 
1) Spawn a Spider
2) Go into an SG game
3) Have someone spectate and see it.

*Miscellaneous Information* 
https://www.youtube.com/watch?v=C8JlPEVFSJY

**Comment by BigFella98** [comment] 2015-01-17 22:59
More evidence - http://imgur.com/z0ECsd2

**Comment by KitMencha** [comment] 2015-01-19 03:10
Duplicate of #498

**Closed by KitMencha** 2015-01-19 03:10 UTC
