### ISSUE TITLE
Holiday Resort 2 - Fence remove Bug -

### ISSUE THREAD

**Issue by xmertsimsek** [MCGamerNetwork/Issues#698] opened 2015-07-03 23:09 UTC
1. Environment
EU SG 1708 3 July 2015 09:15 PM

2. The issue
 I was playing MCSG and ı join 1708. Holiday Resort 2 was selected and ı start searching chests. When ı eating watermelon ı click fence with right click and fence was removed.

3. Steps to reproduce
 1- Join 1708
 2- Holiday Resort 2 was selected.
 3- I start searching chests.
 4- I get hungry
 5- When ı eating watermelon ı click fence with right click
 6- Fence was removed

4. Miscellaneous information
 https://www.youtube.com/watch?v=RkqalH6wWdg

Please remove the above text before submitting your issue report, but DO NOT REMOVE ANYTHING BELOW THIS LINE! The information below this line will help us find the issue faster.
----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 11305).

**Comment by forairan** [comment] 2015-07-15 19:49
Very interesting issue, however I've been unable to reproduce it. Are you using a vanilla (unmodified) client, and have you been able to reproduce it again since the initial video?

**Comment by Nephilim04** [comment] 2015-07-20 12:21
Could this possibly be an issue because the fences are 1.8 blocks?

**Comment by Jodemoted** [comment] 2015-07-30 08:02
This issue occurs because the fences are birch fences, and 1.8 blocks disappear when you right click them while using 1.8. While using 1.7, these blocks do not even appear.

**Comment by forairan** [comment] 2015-07-30 17:16
If that's the case, then this should be fixed the next time the plugin is deployed.
Thanks for the report!

**Closed by forairan** 2015-07-30 17:16 UTC
