### ISSUE TITLE
Battlegrounds Kit Selection Bug/s

### ISSUE THREAD

**Issue by S1kBruZZ** [MCGamerNetwork/Issues#933] opened 2016-03-01 01:39 UTC
Hey lads, I'm sorry there's 3 issues in one report, hopefully it's not too big of a deal, if it is I'll separate them into different issues.

**1. Environment:**
  - **Location**: Australia
  - **GameType**: Battleground
  - **ServerID**: All Battleground Servers.
  - **Time**/**Date**: 29/02/2016 - 11PM (GMT+10:30) 

**2. The issue:**
  - **Issue 1**: Items ended up in the "armor" section of the kit selection. 
     - **Example**: https://gfycat.com/MeagerLividKookaburra
  - **Issue 2**: Items can be dropped from kit selection allowing multiple of the same item.
     - **Example**: https://gfycat.com/DependentCooperativeBlackfly
  - **Issue 3**: Opening compass menu while clicking on sign (or after teleport) then changing your inventory will cause all your items to disappear and your compass to reappear, allowing you to teleport at will.
     - **Example**: https://gfycat.com/AgileGaseousBobwhite

**3. Steps to reproduce**
  - **Issue 1**: I'm not entirely sure how this issue came to be, when the update first came out i was able to move my sword to any slot for a bit, then it was fixed into place.
I did manage to reproduce it another way, which is shown in issue 2. 
> https://gfycat.com/DependentCooperativeBlackfly

  - **Issue 2**: (Works better using Issues 3 Bug)
     1) Open Kit Selection, 
     2) Drop Items 
  - **Issue 3**: 

     1) Select compass in hand slot.
     2) Click and hold right click on a warp sign until menu shows up.

----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 41751).

**Comment by arsenalfcgunners** [comment] 2016-03-01 05:12
Issue #3 is a duplicate of #932 which has already been fixed. The other bugs are as a result of that bug I do believe. I think this has all been fixed, but obviously the devs will confirm.

**Comment by CAmadeusA** [comment] 2016-03-02 07:45
The above issues have been resolved and will be in the next update. Thank you for reporting and have a great day!

**Closed by CAmadeusA** 2016-03-02 07:45 UTC
