### ISSUE TITLE
"Relog Glitch" - Login Order Affects Knockback

### ISSUE THREAD

**Issue by Ceroria** [MCGamerNetwork/Issues#710] opened 2015-07-19 15:09 UTC
This issue occurs on all of our networks, and effects the entire server, however it is only a problem in the gamemodes that require PvP, such as Deadly Descent, Battlegrounds, and Survival Games.  This issue occurs in every match of these gamemodes played. 

This issue is not specific to MCGamer, however there is a way to patch it.  What the issue is, is the order in which a player logs into a server affects the amount of knockback they take, which is a major game-changing factor in the Survival Games.  Say Player A joins the server (1/24) and Player B joins the server (2/24).  Player A will take twice the knockback Player B will take (Player B takes 1 block, Player A takes 2 blocks) therefore any player who logs into the server AFTER another player will have a DISTINCT advantage over the other in a match of Survival Games/Battlegrounds/Deadly Descent.  For further explanation of this glitch, a video has been made by RasclartsReloaded which can be found here https://youtu.be/MesZOuwcuvo, and a thread made on it on the MCGamer Forums can be found here http://www.mcgamer.net/threads/relog-glitch.204172/#post-2075821

This issue can be experienced by simply joining, for example, any Survival Games match. 

This glitch is patchable, and has been patched by most potion PvP servers such as ParaPvP, Kohi, Badlion, etc.

**Comment by forairan** [comment] 2015-09-02 17:25
Spigot seems to have a fix for this; we'll test it out and see what happens.

**Comment by forairan** [comment] 2015-10-07 18:50
Just an update - we're working on a more performance-efficient fix for this issue and are hoping to have it live within the next few days.

**Comment by forairan** [comment] 2015-10-22 16:16
After internal testing, we've determined a couple things: the glitch seems caused by an issue in the 1.7 server (1.8 seems to have patched the issue server-side, as far as I can see), and our fix seems to work to fix it.
That said, this'll be fixed in the next release; thanks for the report!

**Closed by forairan** 2015-10-22 16:16 UTC
