### ISSUE TITLE
Stone sword/Fire

### ISSUE THREAD

**Issue by yannr00s** [MCGamerNetwork/Issues#934] opened 2016-03-01 03:25 UTC
In US SG 661, if you right click a stone sword it would light the block on fire, acting as if the stone sword is a flint and steel.

**Comment by CAmadeusA** [comment] 2016-03-01 03:49
Hey, Im unable to reproduce, is there a specific way that this is triggered?

**Comment by Envici** [comment] 2016-03-01 04:38
Could be an item ghosting situation. I have heard of problems where a player can have nothing in their hand, but be dealing as much damage as a sword.

**Comment by arsenalfcgunners** [comment] 2016-03-01 04:38
What version of MC are you on @yannr00s?

**Comment by arsenalfcgunners** [comment] 2016-03-01 04:39
Yeah it could be that Envici. Probably is in fact.

**Comment by yannr00s** [comment] 2016-03-01 04:49
This was reported to me by DammitDeanne. She was playing on Minecraft 1.8 and I as a spectator on 1.8 saw her holding a stone sword and lighting the blocks on fire.

**Comment by arsenalfcgunners** [comment] 2016-03-01 04:56
If you both saw it then it is probably not an item ghosting... But idk for sure.

**Comment by yannr00s** [comment] 2016-03-01 19:47
I am guessing this is related. I got this video from a community member: https://youtu.be/mhMaZ_SNSqQ

**Comment by CAmadeusA** [comment] 2016-03-02 07:59
This _should_ be resolved in the next update, thank you for reporting and have a great day!

**Closed by CAmadeusA** 2016-03-02 07:59 UTC
