### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by soulknight47** [MCGamerNetwork/Issues#825] opened 2015-10-24 03:01 UTC
https://www.youtube.com/watch?v=V-Rk5C5fsKs&feature=youtu.be fix it

**Comment by InstanceOfDev** [comment] 2015-11-09 03:04
Completely the wrong way to report a bug. Please actually read the proper way to report bugs here:
https://github.com/MCGamerNetwork/Issues

And don't sound like an ass while you're at it. "Fix it" is not the way to ask.

**Comment by forairan** [comment] 2015-11-29 09:38
No information provided by user. Probably a duplicate of #826.

**Closed** 2015-11-29 09:37 UTC
