### ISSUE TITLE
Invisible Players

### ISSUE THREAD

**Issue by LygerByte** [MCGamerNetwork/Issues#548] opened 2015-02-03 16:51 UTC
Since 1.8, whenever I'm in-game sometimes a player comes out invisible, and I can't see or hit him, this happens in before and during deathmatch, or whenever the game starts, the bug happens once a person joins the lobby, I try to stats the player, but it says it doesn't exist. So, if the player is invisible, I guess you can't really do anything ._.

Please fix this issue, it's driving me nuts :(.

**Comment by forairan** [comment] 2015-02-03 23:04
Duplicate of #542.

**Closed by forairan** 2015-02-03 23:04 UTC
