### ISSUE TITLE
/friend not working

### ISSUE THREAD

**Issue by themangotiger** [MCGamerNetwork/Issues#653] opened 2015-05-19 21:28 UTC
When I type /friend list 1 , I am an error saying '/friend list (page)' . Also, when I type /friend or the command to accept friend requests, nothing appears in the chat and the friend requests aren't accepted. This seems to only happen for me as it works for other people. It is happening on the EU servers, in the hub.
----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 2922).

**Comment by forairan** [comment] 2015-05-30 22:48
I'm unable to reproduce this issue; are you still having issues with it?

**Comment by forairan** [comment] 2015-05-30 22:49
Whoops - duplicate of #652. Direct all future comments there, please.

**Closed by forairan** 2015-05-30 22:49 UTC
Labels: cannot-reproduce
