### ISSUE TITLE
Survival Games 2 only map in SG Classic

### ISSUE THREAD

**Issue by MahoganyCrafter** [MCGamerNetwork/Issues#447] opened 2014-12-02 02:08 UTC
I have played many games of SG classic since the release of Xime V2, but every time I have played, the only map choice has been The Survival Games 2, even after 12 skipvotes have been received

**Comment by subv3rsion** [comment] 2015-04-30 20:11
Duplicate of #384

**Closed by subv3rsion** 2015-04-30 20:11 UTC
Labels: maps, Survival Games Classic
