### ISSUE TITLE
1.8 Donor disguise issue

### ISSUE THREAD

**Issue by ProblemFinder** [MCGamerNetwork/Issues#544] opened 2015-02-03 13:39 UTC
Recently after the release of the 1.8 launch, donors that have access to /d in game are able to become invisible towards other players. Thereby allowing them to essentially make it unfair to gold donors and ranks below to see them or hit them, I myself don't know if this issue has been adressed by anyone else but thought it'd be best to post this now.

**Comment by ProblemFinder** [comment] 2015-02-03 13:40
Forgot to mention this aswell, but this has allowed a lot of donors and higher ranks to win games unfairly.

**Comment by ButterScottch** [comment] 2015-02-03 14:04
Duplicate of #542

**Comment by forairan** [comment] 2015-02-03 14:55
Duplicate of #542.

**Closed by forairan** 2015-02-03 14:55 UTC
