### ISSUE TITLE
Friend command broken

### ISSUE THREAD

**Issue by Luflexed** [MCGamerNetwork/Issues#727] opened 2015-07-31 03:39 UTC
1 - This has been an error I have noticed for a while now, and it is an issue globally.

2 - When running the command, /friend requests, it doesn't do anything, so if you were to have a request, you cannot see who added you, therefor you cannot add them to your friends list.

3 - *Blank*

4 - *Blank*

**Comment by forairan** [comment] 2015-08-05 18:22
Duplicate of #695.

**Closed by forairan** 2015-08-05 18:22 UTC
