### ISSUE TITLE
Partytime crashed in middle of a game

### ISSUE THREAD

**Issue by HawK3yLV** [MCGamerNetwork/Issues#587] opened 2015-03-06 17:11 UTC
Hello,

Just to start with, I was playing an EU server, minigame was "Party Time" and the time was about 18:46 .

Today I found a weird issue with one of the minigames. When I joined the "Party Time" minigame, at first it went allright, but a moment later I got warped to an empty arena and my chat just started randomly spamming with various messages from the server.

Not sure if it's possible to reproduce it somehow other than trying the minigame yourself, so, unfortunitely that's all.

![2015-03-06_18 46 00](https://cloud.githubusercontent.com/assets/11353295/6529846/7f3c39d6-c434-11e4-8b80-571c12b088ae.png)

Another thing to note and as you can see, I was using a texture pack that changes the GUI and only GUI for the reasons of inventory transparency (helps in the Hunger Games), but obviously, It shouldn't have anything to do with the server itself

**Comment by subv3rsion** [comment] 2015-04-20 22:11
Duplicate of #271

**Closed by subv3rsion** 2015-04-20 22:11 UTC
Labels: Party Time
